version: '3'
services:

  # dcs-postgres:
  #   image: postgres:15.3-alpine
  #   container_name: dcs-postgres
  #   # restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - default
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

  # dcs-pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: dcs-pgadmin
  #   # restart: always
  #   depends_on:
  #     - dcs-postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dambarreto@localhost.com
  #     PGADMIN_DEFAULT_PASSWORD: maDelA2428
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./data/pgadmin:/var/lib/pgadmin
  
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    ports:
      - 8090:8090
    networks:
      - default

networks:
  default:
    name: local-network
    external: true
    driver: bridge